### ISSUE TITLE
Cannot build a binary

### ISSUE THREAD

**Issue by ritesh** [awslabs/aws-cloudformation-template-builder#1]
I've cloned the repository and I'm trying to build the package but this does not work for me.

Steps followed:
- `git clone https://github.com/awslabs/aws-cloudformation-template-builder.git`
- `cd aws-cloudformation-template-builder.git` 
- `go build`

Output
```
main.go:4:2: cannot find package "codecommit/builders/cfn-skeleton/builder" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/codecommit/builders/cfn-skeleton/builder (from $GOROOT)
	/Users/ritesh/code/go/src/codecommit/builders/cfn-skeleton/builder (from $GOPATH)
util.go:4:2: cannot find package "codecommit/builders/cfn-skeleton/spec" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/codecommit/builders/cfn-skeleton/spec (from $GOROOT)
	/Users/ritesh/code/go/src/codecommit/builders/cfn-skeleton/spec (from $GOPATH)
```
I see there's a build.sh but this does the same for different flavours of `$GOOS`. I think there are refs to packages hosted in codecommit.  For example:

```
$ head main.go
import (
	"codecommit/builders/cfn-skeleton/builder"
	"fmt"
	"os"

	"github.com/awslabs/aws-cloudformation-template-formatter/format"
)
```

Changing `codecommit/builders/cfn-skeleton/builder -> github.com/awslabs/...` does not seem to work either.

**Comment by stilvoid** [comment]
*cough* Whoops. Fixed that now ;)
